version: '3.2'

services:
 mongo:
  image: mongo
  environment:
    - MONGO_INITDB_ROOT_USERNAME=test
    - MONGO_INITDB_ROOT_PASSWORD=test
  ports:
    - "27017:27017"
    - "27018:27018"
    - "27019:27019"

 localstack:
    image: localstack/localstack
    environment:
      - SERVICES=firehose, iam, s3, secretsmanager
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCESS_KEY_ID=test
      - DEFAULT_REGION=eu-west-1
    ports:
        - "4566:4566"
        - "4572:4572"
#       - "4573:4573"
#       - "4593:4593"
#       - "4584:4584"

 minio:
    image: minio/minio
    ports:
            - '9000:9000'
    volumes:
            - ./data/.minio/data:/export
            - ./data/.minio/config:/root/.minio
    environment:
            - MINIO_ACCESS_KEY=testtest
            - MINIO_SECRET_KEY=testtest
    command: server /export

 dynamodb:
     image: amazon/dynamodb-local
     ports:
         - "8000:8000"
     command: ["-jar", "DynamoDBLocal.jar"]

 postgres:
  image: postgres:12
  env_file:
    - .env_file
  ports:
    - "5432:5432"
